# This file contains defaults for optional parameters, which you can override in parameters.yml
parameters:
    locale_fallback: en

    # A secret key that's used to generate certain security-related tokens
    secret: '%env(SYMFONY_SECRET)%'

    # Settings for database backend used by Doctrine DBAL
    # In turn used for default storage engine & default search engine (if legacy is configured as search engine)
    database_driver: '%env(DATABASE_DRIVER)%'
    database_host: '%env(DATABASE_HOST)%'
    database_port: '%env(DATABASE_PORT)%'
    database_name: '%env(DATABASE_NAME)%'
    database_user: '%env(DATABASE_USER)%'
    database_password: '%env(DATABASE_PASSWORD)%'

    # Setting for mail system, used by SwiftMailer
    mailer_host: '%env(MAILER_HOST)%'
    mailer_user: '%env(MAILER_USER)%'
    mailer_password: '%env(MAILER_PASSWORD)%'

    # One of `legacy` (default) or `solr`
    search_engine: '%env(SEARCH_ENGINE)%'

    # Solr root endpoint, relevant if `solr` is set as search_engine
    solr_dsn: '%env(SOLR_DSN)%'
    solr_core: '%env(SOLR_CORE)%'

    # Log path, where to store the log files. php://stderr may be used in order to log to standard error
    log_path: '%env(LOG_PATH)%'

    # Settings for Cache pool, to change add own cache service and optionally inject own arguments
    # predefined pools: see symfony config and the optional pools in app/config/cache_pool/
    cache_pool: '%env(CACHE_POOL)%'

    # Cache DSN, see app/config/services/cache.yml for examples:
    cache_dsn: '%env(CACHE_DSN)%'

    # Settings for HttpCache
    purge_server: '%env(HTTPCACHE_PURGE_SERVER)%'

    # By default cache ttl is set to 24h, when using Varnish you can set a much higher value. High values depends on
    # using EzSystemsPlatformHttpCacheBundle (default as of v1.12) which by design expires affected cache on changes
    httpcache_default_ttl: '%env(HTTPCACHE_DEFAULT_TTL)%'

    # Fallback values for when environment variables do not exist

    env(MAILER_HOST):       127.0.0.1
    env(MAILER_USER):       ~
    env(MAILER_PASSWORD):   ~

    env(SEARCH_ENGINE): legacy

    env(SOLR_DSN): http://localhost:8983/solr
    env(SOLR_CORE): collection1

    env(LOG_PATH): "%kernel.logs_dir%/%kernel.environment%.log"

    env(CACHE_POOL): "cache.app"

    env(CACHE_DSN): localhost

    env(HTTPCACHE_PURGE_SERVER): "http://localhost:80"

    env(HTTPCACHE_DEFAULT_TTL): 86400


    # Compile time handlers
    ## These are defined at compile time, and hence can't be set at runtime using env()
    ## app/config/env/generic.php takes care about letting you set them by env variables

    ## Log type is one of "stream", "error_log" or other types supported by monolog
    log_type: stream

    ## Mail transport used by SwiftMailer
    mailer_transport:  smtp

    # Purge type used by HttpCache system ("local", "varnish"/"http", and on ee also "fastly")
    purge_type: local

    # Admin siteaccess group name
    admin_group_name: admin_group

    # root locationId used for fetching top menu sub items
    home.top_menu.location_id: 2

    # says how many random posts should be displayed on blog post page
    home.blog_post.random_posts_limit: 2

    # locationId used for contact page
    home.layout.contact_location_id: 60

    # says how many blog posts should be shown on home page
    home.home.blog_post_limit: 3

    # locationId used for fetching `blog_post` items on home page
    home.home.blog_location_id: 62

    # says how many images should be shown on home page
    home.home.projects_image_limit: 10

    # locationId used for fetching `image` items on home page
    home.home.projects_location_id: 101

    # says how many images should be shown on home page
    home.home.testimonials_limit: 5

    # locationId used for fetching `image` items on home page
    home.home.testimonials_location_id: 59

    # says how many images should be shown on home page
    home.home.certifications_limit: 50

    # locationId used for fetching `image` items on home page
    home.home.certifications_location_id: 60

    # number of `certification` items displayed per page in the certifications view
    home.certifications_post_list_limit: 8

    # says how many images should be shown on home page
    home.home.services_limit: 4

    # locationId used for fetching `image` items on home page
    home.home.services_location_id: 55

    # says how many images should be shown on home page
    home.home.skills_limit: 8

    # locationId used for fetching `image` items on home page
    home.home.skills_location_id: 56

    # says how many images should be shown on home page
    home.home.personalResume_image_limit: 5

    # locationId used for fetching `image_resume` items on home page
    home.home.personalResume_location_id: 57

    # locationId used for fetching `PDF Resume` items
    home.home.personalResumeCV_location_id : 102

    # number of `project` items displayed per page in the projects view
    home.projects_post_list_limit: 6

    # number of `blog_post` items displayed per page in the blog view
    home.blog_post_list_limit: 5

    # e-mail address used for form submission
    home.contact_form.sender_email: no-reply@ez.no

    # e-mail address used as a message recipient
    home.contact_form.recipient_email: no-reply@ez.no

    # number of images displayed per page
    home.gallery.images_limit: 6