ezpublish:
    system:
        admin:

        site:
            pagelayout: HomeBundle:Default:pagelayout.html.twig
            user:
                layout: HomeBundle:Default:pagelayout.html.twig
                login_template: user\login.html.twig

            user_registration:
                templates:
                    form: user\registration_form.html.twig
                    confirmation: user\registration_confirmation.html.twig

            content_view:
                full:
                    home_page:
                        template: HomeBundle:full:home_page.html.twig
                        params:
                            blog_location_id: '%home.home.blog_location_id%'
                            projects_location_id: '%home.home.projects_location_id%'
                            personalResume_location_id: '%home.home.personalResume_location_id%'
                            contact_location_id: '%home.layout.contact_location_id%'
                            testimonials_location_id: '%home.home.testimonials_location_id%'
                            certifications_location_id: '%home.home.certifications_location_id%'
                            services_location_id: '%home.home.services_location_id%'
                            skills_location_id: '%home.home.skills_location_id%'
                        match:
                            Identifier\ContentType: [home_page]

                    services:
                        controller: app.controller.container:showAction
                        template: HomeBundle:full:services.html.twig
                        match:
                            Identifier\ContentType: [services]

                    skills:
                        controller: app.controller.container:showAction
                        template: HomeBundle:full:skills.html.twig
                        match:
                            Identifier\ContentType: [skills]

                    personalResume:
                        controller: app.controller.container:showAction
                        template: HomeBundle:full:personal_resume.html.twig
                        match:
                            Identifier\ContentType: [resume_gallery]

                    projects:
                        controller: home.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%home.projects_post_list_limit%'
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    location_id: '%home.home.projects_location_id%'
                                assign_results_to: project_posts
                        template: HomeBundle:full:projects.html.twig
                        match:
                            Identifier\ContentType: [projects]

                    testimonials:
                        controller: app.controller.container:showAction
                        template: HomeBundle:full:testimonials.html.twig
                        match:
                            Identifier\ContentType: [testimonials]

                    certifications:
                        controller: home.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%home.certifications_post_list_limit%'
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    location_id: '%home.home.certifications_location_id%'
                                assign_results_to: certifications_posts
                        template: HomeBundle:full:certifications.html.twig
                        match:
                            Identifier\ContentType: [certifications]

                    blog:
                        controller: home.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%home.blog_post_list_limit%'
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    location_id: '%home.home.blog_location_id%'
                                assign_results_to: blog_posts
                        template: HomeBundle:full:blog.html.twig
                        match:
                            Identifier\ContentType: [blog]

                    blog_post:
                        template: HomeBundle:full:blog_post.html.twig
                        match:
                            Identifier\ContentType: [blog_post]

                    contact_form:
                        controller: home.controller.contactform:showContactFormAction
                        template: HomeBundle:full:contact_form.html.twig
                        match:
                            Identifier\ContentType: [contact_form]

                line:
                    blog_post:
                        template: line\blog_post.html.twig
                        match:
                            Identifier\ContentType: [blog_post]

                home:
                    image:
                        template: HomeBundle:home:portfolio.html.twig
                        match:
                            Identifier\ContentType: [image_portfolio]

                    image_resume:
                        template: HomeBundle:home:image_resume.html.twig
                        match:
                            Identifier\ContentType: [image_resume]

                    testimonial:
                        template: HomeBundle:home:testimonials.html.twig
                        match:
                            Identifier\ContentType: [testimonial]

                    certification:
                        template: HomeBundle:home:certification.html.twig
                        match:
                            Identifier\ContentType: [certification]

                    service:
                        template: HomeBundle:home:service.html.twig
                        match:
                            Identifier\ContentType: [service]

                    skill:
                        template: HomeBundle:home:skill.html.twig
                        match:
                            Identifier\ContentType: [skill]

                    blog_post:
                        template: home\blog_post.html.twig
                        match:
                            Identifier\ContentType: [blog_post]

                    contact_form:
                        template: home\contact.html.twig
                        match:
                            Identifier\ContentType: [contact_form]

                    blog:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    limit: '%home.home.blog_post_limit%'
                                    location_id: '%home.home.blog_location_id%'
                                assign_results_to: content_items
                        template: parts\content_list.html.twig
                        match:
                            Identifier\ContentType: [blog]

                    contact_form:
                        controller: home.controller.contactform:showContactFormAction
                        template: parts\contact_form.html.twig
                        match:
                            Identifier\ContentType: [contact_form]

                    projects:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    limit: '%home.home.projects_image_limit%'
                                    location_id: '%home.home.projects_location_id%'
                                assign_results_to: content_items
                        template: HomeBundle:parts:content_list.html.twig
                        match:
                            Identifier\ContentType: [projects]

                    personalResume:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    limit: '%home.home.personalResume_image_limit%'
                                    location_id: '%home.home.personalResume_location_id%'
                                assign_results_to: content_items
                        template: HomeBundle:parts:content_list.html.twig
                        match:
                            Identifier\ContentType: [resume_gallery]

                    testimonials:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    limit: '%home.home.testimonials_limit%'
                                    location_id: '%home.home.testimonials_location_id%'
                                assign_results_to: content_items
                        template: HomeBundle:parts:content_list.html.twig
                        match:
                            Identifier\ContentType: [testimonials]

                    certifications:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    limit: '%home.home.certifications_limit%'
                                    location_id: '%home.home.certifications_location_id%'
                                assign_results_to: content_items
                        template: HomeBundle:parts:content_list.html.twig
                        match:
                            Identifier\ContentType: [certifications]

                    services:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    limit: '%home.home.services_limit%'
                                    location_id: '%home.home.services_location_id%'
                                assign_results_to: content_items
                        template: HomeBundle:parts:content_list.html.twig
                        match:
                            Identifier\ContentType: [services]

                    skills:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    limit: '%home.home.skills_limit%'
                                    location_id: '%home.home.skills_location_id%'
                                assign_results_to: content_items
                        template: HomeBundle:parts:content_list.html.twig
                        match:
                            Identifier\ContentType: [skills]

                blog:
                    blog_posts_list:
                        controller: ez_query:ContentQueryAction
                        params:
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    location_id: '%home.home.blog_location_id%'
                                assign_results_to: blog_posts
                        template: parts\blog_posts_list.html.twig
                        match:
                            Identifier\ContentType: [blog]

                blog_post:
                    random_blog_posts:
                        controller: ez_query:ContentQueryAction
                        params:
                            random_posts_limit: '%home.blog_post.random_posts_limit%'
                            query:
                                query_type: HomeBundle:LatestContent
                                parameters:
                                    location_id: '%home.home.blog_location_id%'
                                assign_results_to: random_blog_posts
                        template: parts\random_blog_posts.html.twig
                        match:
                            Identifier\ContentType: [blog_post]

            field_templates:
                - { template: HomeBundle:Default:content_fields.html.twig, priority: 100 }
