ezpublish:
    system:
        default:
            pagelayout: pagelayout.html.twig
            user:
                layout: pagelayout.html.twig
                login_template: user\login.html.twig

            user_registration:
                templates:
                    form: user\registration_form.html.twig
                    confirmation: user\registration_confirmation.html.twig

            content_view:
                full:
                    home_page:
                        template: full\home_page.html.twig
                        params:
                            blog_location_id: '%app.home.blog_location_id%'
                            gallery_location_id: '%app.home.gallery_location_id%'
                            personalResume_location_id: '%app.home.personalResume_location_id%'
                            contact_location_id: '%app.layout.contact_location_id%'
                            testimonials_location_id: '%app.home.testimonials_location_id%'
                            certifications_location_id: '%app.home.certifications_location_id%'
                            services_location_id: '%app.home.services_location_id%'
                            skills_location_id: '%app.home.skills_location_id%'
                        match:
                            Identifier\ContentType: [home_page]

                    blog:
                        controller: app.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%app.blog_post_list_limit%'
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    location_id: '%app.home.blog_location_id%'
                                assign_results_to: blog_posts
                        template: full\blog.html.twig
                        match:
                            Identifier\ContentType: [blog]

                    blog_post:
                        template: full\blog_post.html.twig
                        match:
                            Identifier\ContentType: [blog_post]

                    contact_form:
                        controller: app.controller.contactform:showContactFormAction
                        template: full\contact_form.html.twig
                        match:
                            Identifier\ContentType: [contact_form]

                    gallery:
                        controller: app.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%app.gallery.images_limit%'
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    location_id: '%app.home.gallery_location_id%'
                                assign_results_to: images
                        template: full\gallery.html.twig
                        match:
                            Identifier\ContentType: [gallery]

                    personalResume:
                        controller: app.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%app.home.personalresume_image_limit%'
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    location_id: '%app.home.personalResume_location_id%'
                                assign_results_to: images
                        template: full\personalResume.html.twig
                        match:
                            Identifier\ContentType: [resume_gallery]

                    testimonials:
                        controller: app.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%app.home.testimonials_limit%'
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    location_id: '%app.home.testimonials_location_id%'
                                assign_results_to: images
                        template: full\testimonials.html.twig
                        match:
                            Identifier\ContentType: [testimonials]

                    certifications:
                        controller: app.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%app.home.certifications_limit%'
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    location_id: '%app.home.certifications_location_id%'
                                assign_results_to: images
                        template: full\certifications.html.twig
                        match:
                            Identifier\ContentType: [certifications]

                    services:
                        controller: app.paginated_query_controller:contentQueryPaginationAction
                        params:
                            page_limit: '%app.home.services_limit%'
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    location_id: '%app.home.services_location_id%'
                                assign_results_to: images
                        template: full\services.html.twig
                        match:
                            Identifier\ContentType: [services]

                line:
                    blog_post:
                        template: line\blog_post.html.twig
                        match:
                            Identifier\ContentType: [blog_post]

                home:
                    image:
                        template: home\portfolio.html.twig
                        match:
                            Identifier\ContentType: [image_portfolio]

                    image_resume:
                        template: home\image_resume.html.twig
                        match:
                            Identifier\ContentType: [image_resume]

                    testimonial:
                        template: home\testimonials.html.twig
                        match:
                            Identifier\ContentType: [testimonial]

                    certification:
                        template: home\certification.html.twig
                        match:
                            Identifier\ContentType: [certification]

                    service:
                        template: home\service.html.twig
                        match:
                            Identifier\ContentType: [service]

                    skill:
                        template: home\skill.html.twig
                        match:
                            Identifier\ContentType: [skill]

                    blog_post:
                        template: home\blog_post.html.twig
                        match:
                            Identifier\ContentType: [blog_post]

                    contact_form:
                        template: home\contact.html.twig
                        match:
                            Identifier\ContentType: [contact_form]

                    blog:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    limit: '%app.home.blog_post_limit%'
                                    location_id: '%app.home.blog_location_id%'
                                assign_results_to: content_items
                        template: parts\content_list.html.twig
                        match:
                            Identifier\ContentType: [blog]

                    contact_form:
                        controller: app.controller.contactform:showContactFormAction
                        template: parts\contact_form.html.twig
                        match:
                            Identifier\ContentType: [contact_form]

                    gallery:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    limit: '%app.home.gallery_image_limit%'
                                    location_id: '%app.home.gallery_location_id%'
                                assign_results_to: content_items
                        template: parts\content_list.html.twig
                        match:
                            Identifier\ContentType: [gallery]

                    personalResume:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    limit: '%app.home.personalResume_image_limit%'
                                    location_id: '%app.home.personalResume_location_id%'
                                assign_results_to: content_items
                        template: parts\content_list.html.twig
                        match:
                            Identifier\ContentType: [resume_gallery]

                    testimonials:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    limit: '%app.home.testimonials_limit%'
                                    location_id: '%app.home.testimonials_location_id%'
                                assign_results_to: content_items
                        template: parts\content_list.html.twig
                        match:
                            Identifier\ContentType: [testimonials]

                    certifications:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    limit: '%app.home.certifications_limit%'
                                    location_id: '%app.home.certifications_location_id%'
                                assign_results_to: content_items
                        template: parts\content_list.html.twig
                        match:
                            Identifier\ContentType: [certifications]

                    services:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    limit: '%app.home.services_limit%'
                                    location_id: '%app.home.services_location_id%'
                                assign_results_to: content_items
                        template: parts\content_list.html.twig
                        match:
                            Identifier\ContentType: [services]

                    skills:
                        controller: ez_query:ContentQueryAction
                        params:
                            view_type: home
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    limit: '%app.home.skills_limit%'
                                    location_id: '%app.home.skills_location_id%'
                                assign_results_to: content_items
                        template: parts\content_list.html.twig
                        match:
                            Identifier\ContentType: [skills]

                blog:
                    blog_posts_list:
                        controller: ez_query:ContentQueryAction
                        params:
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    location_id: '%app.home.blog_location_id%'
                                assign_results_to: blog_posts
                        template: parts\blog_posts_list.html.twig
                        match:
                            Identifier\ContentType: [blog]

                blog_post:
                    random_blog_posts:
                        controller: ez_query:ContentQueryAction
                        params:
                            random_posts_limit: '%app.blog_post.random_posts_limit%'
                            query:
                                query_type: AppBundle:LatestContent
                                parameters:
                                    location_id: '%app.home.blog_location_id%'
                                assign_results_to: random_blog_posts
                        template: parts\random_blog_posts.html.twig
                        match:
                            Identifier\ContentType: [blog_post]

            field_templates:
                - { template: content_fields.html.twig, priority: 100 }
