services:
    home.paginated_query_controller:
        class: HomeBundle\Controller\PagerFantaQueryController
        arguments:
            - '@ezpublish.query_type_content_view_mapper'
            - '@ezpublish.api.service.search'

    home.controller.menu:
        class: HomeBundle\Controller\MenuController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@home.query_type.menu'
            - '%home.top_menu.location_id%'

    home.controller.contactform:
        class: HomeBundle\Controller\ContactFormController
        arguments:
            - '@form.factory'
            - '@home.mail.sender'
            - '@templating'
            - '@hautelook.router.template'
