services:
    home.mail.sender:
        class: HomeBundle\Mail\Sender
        arguments:
            - '@mailer'
            - '@translator'
            - '@templating'
            - '%home.contact_form.sender_email%'
            - '%home.contact_form.recipient_email%'
