services:
    home.query_type.latest_content:
        class: HomeBundle\QueryType\LatestContentQueryType
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - { name: ezpublish.query_type }

    home.query_type.menu:
        class: HomeBundle\QueryType\MenuQueryType
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - { name: ezpublish.query_type }
