services:
#    home.example:
#        class: HomeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.criteria.children:
        class: HomeBundle\Criteria\Children

    app.controller.container:
        class: HomeBundle\Controller\ContainerController
        arguments:
            - '@ezpublish.api.service.search'
            - '@ezpublish.config.resolver'
            - '@app.criteria.children'

    app.controller.twitter:
        class: HomeBundle\Controller\TwitterController
        arguments: ['@service_container']